version: '3.8'

services:
  daffigard-robin-billys:
    image: ghcr.io/hampusmattsson1/daffigard:0.1.2-robin
    container_name: daffigard-robin-billys
    shm_size: '2gb' # Critical for Playwright/Chromium in Docker to prevent crashes/timeouts
    environment:
      - INSTANCE_COUNT=1
      - LOW_RESOURCE=false
      - PROFILE=robin-billys
      - VARIANT=billys
    deploy:
      resources:
        limits:
          cpus: 1
          memory: 2Gi
    #volumes:
      # Maps your local persistent profile directory into the container's app path
      #- ./user-robin-billys:/app/user-robin-billys