apiVersion: apps/v1
kind: Deployment
metadata:
  name: daffigard-hampus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: daffigard-hampus
  template:
    metadata:
      labels:
        app: daffigard-hampus
    spec:
      containers:
      - name: daffigard-hampus
        image: ghcr.io/hampus-mattsson_rbl/daffigard:0.1.1
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: "2Gi"
            cpu: "1"
        env:
          - name: INSTANCE_COUNT
            value: "2"
          - name: LOW_RESOURCE
            value: "true"
          - name: PROFILE
            value: "hampus"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: daffigard-sharif
spec:
  replicas: 1
  selector:
    matchLabels:
      app: daffigard-sharif
  template:
    metadata:
      labels:
        app: daffigard-sharif
    spec:
      containers:
      - name: daffigard-sharif
        image: ghcr.io/hampus-mattsson_rbl/daffigard:0.1.1
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: "2Gi"
            cpu: "1"
        env:
          - name: INSTANCE_COUNT
            value: "2"
          - name: LOW_RESOURCE
            value: "true"
          - name: PROFILE
            value: "sharif"
