# Dafgård
apiVersion: apps/v1
kind: Deployment
metadata:
  name: daffigard-hampus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: daffigard-hampus
  template:
    metadata:
      labels:
        app: daffigard-hampus
    spec:
      containers:
      - name: daffigard-hampus
        image: ghcr.io/hampusmattsson1/daffigard:0.1.2
        imagePullPolicy: IfNotPresent
        # resources:
        #   limits:
        #     memory: "2Gi"
        #     cpu: "1"
        env:
          - name: INSTANCE_COUNT
            value: "2"
          - name: PROFILE
            value: "hampus"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: daffigard-sharif
spec:
  replicas: 1
  selector:
    matchLabels:
      app: daffigard-sharif
  template:
    metadata:
      labels:
        app: daffigard-sharif
    spec:
      containers:
      - name: daffigard-sharif
        image: ghcr.io/hampusmattsson1/daffigard:0.1.2
        imagePullPolicy: IfNotPresent
        # resources:
        #   limits:
        #     memory: "2Gi"
        #     cpu: "1"
        env:
          - name: INSTANCE_COUNT
            value: "2"
          - name: PROFILE
            value: "sharif"

---

# Billys

apiVersion: apps/v1
kind: Deployment
metadata:
  name: daffigard-hampus-billys
spec:
  replicas: 1
  selector:
    matchLabels:
      app: daffigard-hampus-billys
  template:
    metadata:
      labels:
        app: daffigard-hampus-billys
    spec:
      containers:
      - name: daffigard-hampus-billys
        image: ghcr.io/hampusmattsson1/daffigard:0.1.2
        imagePullPolicy: IfNotPresent
        # resources:
        #   limits:
        #     memory: "2Gi"
        #     cpu: "1"
        env:
          - name: INSTANCE_COUNT
            value: "2"
          - name: PROFILE
            value: "hampus-billys"
          - name: VARIANT
            value: "billys"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: daffigard-sharif-billys
spec:
  replicas: 1
  selector:
    matchLabels:
      app: daffigard-sharif-billys
  template:
    metadata:
      labels:
        app: daffigard-sharif-billys
    spec:
      containers:
      - name: daffigard-sharif-billys
        image: ghcr.io/hampusmattsson1/daffigard:0.1.2
        imagePullPolicy: IfNotPresent
        # resources:
        #   limits:
        #     memory: "2Gi"
        #     cpu: "1"
        env:
          - name: INSTANCE_COUNT
            value: "2"
          - name: PROFILE
            value: "sharif-billys"
          - name: VARIANT
            value: "billys"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: daffigard-jonas-billys
spec:
  replicas: 1
  selector:
    matchLabels:
      app: daffigard-jonas-billys
  template:
    metadata:
      labels:
        app: daffigard-jonas-billys
    spec:
      containers:
      - name: daffigard-jonas-billys
        image: ghcr.io/hampusmattsson1/daffigard:0.1.2
        imagePullPolicy: IfNotPresent
        # resources:
        #   limits:
        #     memory: "2Gi"
        #     cpu: "1"
        env:
          - name: INSTANCE_COUNT
            value: "2"
          - name: PROFILE
            value: "jonas-billys"
          - name: VARIANT
            value: "billys"

---

# Robin
apiVersion: apps/v1
kind: Deployment
metadata:
  name: daffigard-robin-billys
spec:
  replicas: 1
  selector:
    matchLabels:
      app: daffigard-robin-billys
  template:
    metadata:
      labels:
        app: daffigard-robin-billys
    spec:
      containers:
      - name: daffigard-robin-billys
        image: ghcr.io/hampusmattsson1/daffigard:0.1.2-robin
        imagePullPolicy: IfNotPresent
        # resources:
        #   limits:
        #     memory: "2Gi"
        #     cpu: "1"
        env:
          - name: INSTANCE_COUNT
            value: "2"
          - name: PROFILE
            value: "robin-billys"
          - name: VARIANT
            value: "billys"

---

# Devine
apiVersion: apps/v1
kind: Deployment
metadata:
  name: daffigard-devine-billys
spec:
  replicas: 1
  selector:
    matchLabels:
      app: daffigard-devine-billys
  template:
    metadata:
      labels:
        app: daffigard-devine-billys
    spec:
      containers:
      - name: daffigard-devine-billys
        image: ghcr.io/hampusmattsson1/daffigard:0.1.2-devine
        imagePullPolicy: IfNotPresent
        # resources:
        #   limits:
        #     memory: "2Gi"
        #     cpu: "1"
        env:
          - name: INSTANCE_COUNT
            value: "2"
          - name: PROFILE
            value: "devine-billys"
          - name: VARIANT
            value: "billys"

---

# Simon Billys & Erik någon

apiVersion: apps/v1
kind: Deployment
metadata:
  name: daffigard-simon
spec:
  replicas: 1
  selector:
    matchLabels:
      app: daffigard-simon
  template:
    metadata:
      labels:
        app: daffigard-simon
    spec:
      containers:
      - name: daffigard-simon
        image: ghcr.io/hampusmattsson1/daffigard:0.1.2
        imagePullPolicy: IfNotPresent
        # resources:
        #   limits:
        #     memory: "2Gi"
        #     cpu: "1"
        env:
          - name: INSTANCE_COUNT
            value: "2"
          - name: PROFILE
            value: "simon"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: daffigard-simon-billys
spec:
  replicas: 1
  selector:
    matchLabels:
      app: daffigard-simon-billys
  template:
    metadata:
      labels:
        app: daffigard-simon-billys
    spec:
      containers:
      - name: daffigard-simon-billys
        image: ghcr.io/hampusmattsson1/daffigard:0.1.2-simonerik
        imagePullPolicy: IfNotPresent
        # resources:
        #   limits:
        #     memory: "2Gi"
        #     cpu: "1"
        env:
          - name: INSTANCE_COUNT
            value: "2"
          - name: PROFILE
            value: "simon-billys"
          - name: VARIANT
            value: "billys"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: daffigard-erik
spec:
  replicas: 1
  selector:
    matchLabels:
      app: daffigard-erik
  template:
    metadata:
      labels:
        app: daffigard-erik
    spec:
      containers:
      - name: daffigard-erik
        image: ghcr.io/hampusmattsson1/daffigard:0.1.2-simonerik
        imagePullPolicy: IfNotPresent
        # resources:
        #   limits:
        #     memory: "2Gi"
        #     cpu: "1"
        env:
          - name: INSTANCE_COUNT
            value: "2"
          - name: PROFILE
            value: "erik"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: daffigard-erik-billys
spec:
  replicas: 1
  selector:
    matchLabels:
      app: daffigard-erik-billys
  template:
    metadata:
      labels:
        app: daffigard-erik-billys
    spec:
      containers:
      - name: daffigard-erik-billys
        image: ghcr.io/hampusmattsson1/daffigard:0.1.2-simonerik
        imagePullPolicy: IfNotPresent
        # resources:
        #   limits:
        #     memory: "2Gi"
        #     cpu: "1"
        env:
          - name: INSTANCE_COUNT
            value: "2"
          - name: PROFILE
            value: "erik-billys"
          - name: VARIANT
            value: "billys"