# Global default container settings
image:
  repository: ghcr.io/hampusmattsson1/daffigard
  tag: 0.2.0-fast
  pullPolicy: IfNotPresent

instanceCount: "2"

resources:
  requests:
    memory: "500Mi"
    cpu: "300m"
  limits:
    memory: "1Gi"
    cpu: "750m"

persistence:
  enabled: false  # Set to true to enable PVC mount
  claimName: daffigard-pvc
  mountPath: /data

# List of game automation instances
instances:
  - name: hampus
    profile: "hampus"

  - name: sharif
    profile: "sharif"

  - name: hampus-billys
    profile: "hampus-billys"
    variant: "billys"

  - name: sharif-billys
    profile: "sharif-billys"
    variant: "billys"

  - name: jonas-billys
    profile: "jonas-billys"
    variant: "billys"

  - name: robin-billys
    profile: "robin-billys"
    variant: "billys"
    # image:
      # tag: "0.1.2-robin"

  - name: devine-billys
    profile: "devine-billys"
    variant: "billys"
    # image:
      # tag: "0.1.2-devine"

  - name: simon
    profile: "simon"

  - name: simon-billys
    profile: "simon-billys"
    variant: "billys"
    # image:
      # tag: "0.1.2-simonerik"

  - name: erik
    profile: "erik"
    # image:
      # tag: "0.1.2-simonerik"

  - name: erik-billys
    profile: "erik-billys"
    variant: "billys"
    # image:
      # tag: "0.1.2-simonerik"