# Dafgård
apiVersion: apps/v1
kind: Deployment
metadata:
  name: daffigard-simon
spec:
  replicas: 1
  selector:
    matchLabels:
      app: daffigard-simon
  template:
    metadata:
      labels:
        app: daffigard-simon
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
      - name: daffigard-simon
        image: ghcr.io/hampus-mattsson_rbl/daffigard:0.1.2
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: "2Gi"
            cpu: "1"
        readinessProbe:
          exec:
            command:
            - test
            - -d
            - /tmp/user-data-1
          initialDelaySeconds: 10
          periodSeconds: 10
        env:
          - name: INSTANCE_COUNT
            value: "2"
          - name: LOW_RESOURCE
            value: "false"
          - name: PROFILE
            value: "simon"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: daffigard-hampus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: daffigard-hampus
  template:
    metadata:
      labels:
        app: daffigard-hampus
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
      - name: daffigard-hampus
        image: ghcr.io/hampus-mattsson_rbl/daffigard:0.1.2
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: "2Gi"
            cpu: "1"
        env:
          - name: INSTANCE_COUNT
            value: "2"
          - name: LOW_RESOURCE
            value: "false"
          - name: PROFILE
            value: "hampus"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: daffigard-sharif
spec:
  replicas: 1
  selector:
    matchLabels:
      app: daffigard-sharif
  template:
    metadata:
      labels:
        app: daffigard-sharif
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
      - name: daffigard-sharif
        image: ghcr.io/hampus-mattsson_rbl/daffigard:0.1.2
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: "2Gi"
            cpu: "1"
        env:
          - name: INSTANCE_COUNT
            value: "2"
          - name: LOW_RESOURCE
            value: "false"
          - name: PROFILE
            value: "sharif"

---

# Billys

apiVersion: apps/v1
kind: Deployment
metadata:
  name: daffigard-hampus-billys
spec:
  replicas: 1
  selector:
    matchLabels:
      app: daffigard-hampus-billys
  template:
    metadata:
      labels:
        app: daffigard-hampus-billys
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
      - name: daffigard-hampus-billys
        image: ghcr.io/hampus-mattsson_rbl/daffigard:0.1.2
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: "2Gi"
            cpu: "1"
        env:
          - name: INSTANCE_COUNT
            value: "2"
          - name: LOW_RESOURCE
            value: "false"
          - name: PROFILE
            value: "hampus-billys"
          - name: VARIANT
            value: "billys"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: daffigard-sharif-billys
spec:
  replicas: 1
  selector:
    matchLabels:
      app: daffigard-sharif-billys
  template:
    metadata:
      labels:
        app: daffigard-sharif-billys
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
      - name: daffigard-sharif-billys
        image: ghcr.io/hampus-mattsson_rbl/daffigard:0.1.2
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: "2Gi"
            cpu: "1"
        env:
          - name: INSTANCE_COUNT
            value: "2"
          - name: LOW_RESOURCE
            value: "false"
          - name: PROFILE
            value: "sharif-billys"
          - name: VARIANT
            value: "billys"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: daffigard-jonas-billys
spec:
  replicas: 1
  selector:
    matchLabels:
      app: daffigard-jonas-billys
  template:
    metadata:
      labels:
        app: daffigard-jonas-billys
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
      - name: daffigard-jonas-billys
        image: ghcr.io/hampus-mattsson_rbl/daffigard:0.1.2
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: "2Gi"
            cpu: "1"
        env:
          - name: INSTANCE_COUNT
            value: "2"
          - name: LOW_RESOURCE
            value: "false"
          - name: PROFILE
            value: "jonas-billys"
          - name: VARIANT
            value: "billys"